import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
// import ReduxProvider from "@/redux/provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <ReduxProvider> */}
        <div className="bg-white flex min-h-screen flex-col items-center justify-between p-24">
          <Header />
          <div className="my-8">{children}</div>
        </div>
        {/* </ReduxProvider> */}
      </body>
    </html>
  );
}
